### ISSUE TITLE
Mejorar el panel de consultas pasadas que realizo un Doctor.

### ISSUE THREAD

**Issue by BetweenShadows** [BetweenShadows/Gestion-de-clinica-medica#4]
Se pueden tomar las siguientes consideraciones:
1. Agregar la fecha y la hora a la  tabla.
2. Quitar el panel adyacente a la tabla y reutilizar el panel de realizar consulta para ver la consulta pasada.
3. Filtrar las consultadas pasadas utilizando el nombre del paciente. A medida que se escriba en el TextField del nombre, se va actualizando la tabla.

**Comment by AliciaC07** [comment]
Parte #3 realizada.
